version: '3'

services:
  resource-service:
    build: './resource-service'
    depends_on:
      - 'resource-db'
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${RESOURCE_SERVER_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_SERVER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_SERVER_DB_PASSWORD}
      SONG_SERVICE_URL: ${RESOURCE_SERVER_SONG_SERVICE_URL}

  song-service:
    build: './song-service'
    depends_on:
      - 'song-db'
    ports:
      - '8082:8082'
    environment:
      SPRING_DATASOURCE_URL: ${SONG_SERVER_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SONG_SERVER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SONG_SERVER_DB_PASSWORD}
      SERVER_PORT: ${SONG_SERVER_PORT}

  resource-db:
    image: 'postgres:17-alpine'
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: ${RESOURCE_DB}
      POSTGRES_USER: ${RESOURCE_DB_USER}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    volumes:
      - './init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql'

  song-db:
    image: 'postgres:17-alpine'
    ports:
      - '5435:5432'
    environment:
      POSTGRES_DB: ${SONG_DB}
      POSTGRES_USER: ${SONG_DB_USER}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    volumes:
      - './init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql'