spring:
  application:
    name: microservices-foundation
  datasource:
    url: jdbc:postgresql://localhost:5435/song-db
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port : 8082
