spring:
  application:
    name: discovery-service
server:
  port: ${SERVER_PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
