spring:
  application:
    name: microservices-foundation
  datasource:
    url: jdbc:postgresql://localhost:5434/resource-db
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

song.service.url: http://localhost:8082