spring:
  application:
    name: microservices-foundation
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/resource-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

song.service.url: ${SONG_SERVICE_URL:http://localhost:8082}